# Generated by Django 5.1.1 on 2024-11-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0002_task_assigned_group_task_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='analista',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assigned_group',
            new_name='equipe_desenvolvimento',
        ),
    ]
