# Generated by Django 5.1.1 on 2024-11-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0003_rename_assigned_to_task_analista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo de Conclusão'),
        ),
    ]
